import React from 'react';
import { Link } from 'react-router-dom';
export default function Home({ lang='ru' }) {
  const zh=lang==='zh';
  return <div className="sv"><section className="sv-hero"><div><span className="sv-eyebrow">SKYVISION · {zh?'哈萨克斯坦 → 中国':'КАЗАХСТАН → КИТАЙ'}</span><h1>{zh?'连接工厂、采购商与物流企业。':'Заводы и логистика. Прямой контакт.'}</h1><p>{zh?'寻找产品与运输报价，发布企业广告，发送申请并直接与合作伙伴沟通。':'Находите продукцию и перевозки, размещайте предложения своей компании и обсуждайте условия с партнёрами в личном кабинете.'}</p><div className="sv-actions"><Link className="sv-button" to="/marketplace">{zh?'浏览市场':'Открыть маркетплейс'} →</Link><Link className="sv-button secondary" to="/portal">{zh?'企业工作空间':'Кабинет компании'}</Link></div><div className="sv-hero-labels"><span>FCA / DAP</span><span>USD / {zh?'吨':'тонна'}</span><span>RU / 中文</span></div></div><div className="sv-hero-visual"><img src="/photos/harvest/harvest/photo1.jpeg" alt={zh?'工厂与产品':'Производство и продукция'} /><div><span>{zh?'从信息到订单':'От выбора к заявке'}</span><strong>{zh?'工厂 · 产品 · 物流':'Заводы · Продукция · Логистика'}</strong></div></div></section>
    <section className="sv-section"><span className="sv-eyebrow">{zh?'采购流程':'КАК ЭТО РАБОТАЕТ'}</span><h2>{zh?'做出采购决定所需的信息':'Всё, чтобы выбрать поставщика'}</h2><div className="sv-steps">{(zh?[['01','比较价格','按城市和产品筛选，比较 FCA 价格及运费。'],['02','了解工厂','查看生产照片、产品特性、证书及检测报告。'],['03','联系合作伙伴','从企业账户发送申请，与供应商或货运代理直接讨论条件。']]:[['01','Сравните предложения','Выберите город и продукцию. Сравните FCA и стоимость доставки до нужного пункта.'],['02','Изучите завод','Посмотрите фото производства, характеристики, сертификаты и протоколы испытаний.'],['03','Свяжитесь с компанией','Войдите в кабинет, выберите объявление и обсудите условия с заводом или экспедитором.']]).map(([n,h,p])=><article className="sv-card" key={n}><span className="sv-step-number">{n}</span><h3>{h}</h3><p>{p}</p></article>)}</div></section>
    <section className="sv-card sv-how"><div><span className="sv-eyebrow">FCA + {zh?'物流':'ЛОГИСТИКА'} → DAP</span><h2>{zh?'价格与路线，清晰呈现':'Цена товара и доставка — отдельно'}</h2><p>{zh?'每个目的地采用单独的运输费率。未确认的价格显示为“请咨询”，历史报价带有提示。':'Для каждого направления можно задать свой тариф. Если цена ещё не подтверждена, вы увидите пометку, а недостающую стоимость сможете запросить у менеджера.'}</p></div><Link className="sv-button" to="/prices">{zh?'进入目录':'Перейти в каталог'} →</Link></section>
  </div>;
}
