import React from 'react';
import { Link } from 'react-router-dom';
export default function Home({ lang='ru', openModal }) {
  const zh=lang==='zh';
  return <div className="sv"><section className="sv-hero"><div><span className="sv-eyebrow">SKYVISION · {zh?'哈萨克斯坦 → 中国':'КАЗАХСТАН → КИТАЙ'}</span><h1>{zh?'从工厂选择产品，安排可靠交付。':'От завода — к вашей поставке.'}</h1><p>{zh?'比较饲料面粉及其他产品的价格，查看工厂照片和检测报告，向我们提交采购需求。':'Сравните цены на кормовую муку и другую продукцию, изучите заводы и документы. Мы поможем согласовать покупку и доставку.'}</p><div className="sv-actions"><Link className="sv-button" to="/prices">{zh?'查看工厂与价格':'Смотреть заводы и цены'} →</Link><button className="secondary" onClick={()=>openModal(zh?'采购与物流咨询':'Подбор продукции и логистики')}>{zh?'联系经理':'Обсудить поставку'}</button></div><div className="sv-hero-labels"><span>FCA / DAP</span><span>USD / {zh?'吨':'тонна'}</span><span>RU / 中文</span></div></div><div className="sv-hero-visual"><img src="/photos/harvest/harvest/photo1.jpeg" alt={zh?'工厂与产品':'Производство и продукция'} /><div><span>{zh?'从信息到订单':'От выбора к заявке'}</span><strong>{zh?'工厂 · 产品 · 物流':'Заводы · Продукция · Логистика'}</strong></div></div></section>
    <section className="sv-section"><span className="sv-eyebrow">{zh?'采购流程':'КАК ЭТО РАБОТАЕТ'}</span><h2>{zh?'做出采购决定所需的信息':'Всё, чтобы выбрать поставщика'}</h2><div className="sv-steps">{(zh?[['01','比较价格','按城市和产品筛选，比较 FCA 价格及运费。'],['02','了解工厂','查看生产照片、产品特性、证书及检测报告。'],['03','提交需求','选择产品与目的地，经理将确认价格和供货条件。']]:[['01','Сравните предложения','Выберите город и продукцию. Сравните FCA и стоимость доставки до нужного пункта.'],['02','Изучите завод','Посмотрите фото производства, характеристики, сертификаты и протоколы испытаний.'],['03','Отправьте заявку','Укажите продукцию и направление. Менеджер подтвердит цену и условия поставки.']]).map(([n,h,p])=><article className="sv-card" key={n}><span className="sv-step-number">{n}</span><h3>{h}</h3><p>{p}</p></article>)}</div></section>
    <section className="sv-card sv-how"><div><span className="sv-eyebrow">FCA + {zh?'物流':'ЛОГИСТИКА'} → DAP</span><h2>{zh?'价格与路线，清晰呈现':'Цена товара и доставка — отдельно'}</h2><p>{zh?'每个目的地采用单独的运输费率。未确认的价格显示为“请咨询”，历史报价带有提示。':'Для каждого направления можно задать свой тариф. Если цена ещё не подтверждена, вы увидите пометку, а недостающую стоимость сможете запросить у менеджера.'}</p></div><Link className="sv-button" to="/prices">{zh?'进入目录':'Перейти в каталог'} →</Link></section>
  </div>;
}
