import React, { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { supabase } from '../lib/supabaseClient';
import { useCompany } from './CompanyContext';
import { canEdit, listingName, listingPrice, result } from './api';
import { Empty, Feedback, Loading, RequestForm, useLoad } from './Portal';
import { Media } from './Network';
import { downloadFile, uploadFile } from './files';

export default function CompanyPage({lang}){
  const zh=lang==='zh';const {id}=useParams();const ctx=useCompany();const [editing,setEditing]=useState(false);const [active,setActive]=useState('');
  const state=useLoad(async()=>({company:await result(supabase.from('sv_companies').select('id,name,name_zh,city,country,activities').eq('id',id).maybeSingle()),page:await result(supabase.from('sv_company_pages').select('*').eq('company_id',id).maybeSingle()),assets:await result(supabase.from('sv_company_assets').select('*').eq('company_id',id).order('created_at',{ascending:false})),listings:await result(supabase.from('sv_listings').select('*').eq('company_id',id).eq('status','published').order('updated_at',{ascending:false}).limit(100))}),[id]);
  if(state.loading)return <div className="sv"><Loading zh={zh}/></div>;if(state.error)return <div className="sv"><Feedback error={state.error} zh={zh}/></div>;if(!state.data.company)return <div className="sv"><Empty title={zh?'企业资料尚未公开':'Страница компании пока недоступна'} text={zh?'企业发布广告后，公开资料将显示在此。':'Публичная страница появляется после публикации объявления.'}/></div>;
  const {company,page,assets,listings}=state.data;const member=ctx.memberships.find(m=>m.company_id===id);const edit=canEdit(member?.role);const name=(zh&&company.name_zh)||company.name;
  return <div className="sv sp"><Link to="/marketplace">← {zh?'市场':'Маркетплейс'}</Link><section className="sn-company-hero"><span className="sv-eyebrow" style={{color:'#a8d7ff'}}>{zh?'企业主页':'СТРАНИЦА КОМПАНИИ'}</span><h1>{name}</h1><p>{company.country} · {company.city}</p><div className="sp-tags">{company.activities.map(a=><span className="sp-tag" key={a}>{{factory:zh?'工厂':'Завод',forwarder:zh?'物流公司':'Экспедитор',buyer:zh?'采购商':'Покупатель'}[a]}</span>)}<span className="sp-tag">{zh?'企业未经认证':'Компания не проверена'}</span></div></section>{edit&&<button className="secondary" onClick={()=>setEditing(v=>!v)}>{editing?(zh?'关闭编辑':'Закрыть редактор'):(zh?'编辑企业主页':'Редактировать страницу компании')}</button>}{editing&&edit&&<CompanyEditor companyId={id} page={page} assets={assets} zh={zh} onDone={()=>{setEditing(false);state.reload();}}/>}<section className="sv-section"><h2>{zh?'关于公司':'О компании'}</h2><p className="sp-description">{(zh&&page?.about_zh)||page?.about||(zh?'公司尚未添加介绍。':'Компания ещё не добавила описание.')}</p>{page?.capacity&&<p><strong>{zh?'产能与供应量':'Объёмы и возможности'}: </strong>{page.capacity}</p>}{page?.website?.startsWith('https://')&&<a href={page.website} target="_blank" rel="noopener noreferrer">{zh?'公司网站':'Сайт компании'} ↗</a>}</section><section className="sv-section"><h2>{zh?'照片、视频与文件':'Фото, видео и документы'}</h2><div className="sn-media-grid">{assets.map(a=><CompanyAsset key={a.id} asset={a} zh={zh}/>)}</div>{!assets.length&&<p className="sv-muted">{zh?'还没有上传的资料。':'Материалы пока не добавлены.'}</p>}</section><section><h2>{zh?'企业报价':'Предложения компании'}</h2><div className="sp-grid">{listings.map(l=><article className="sv-card" key={l.id}><h2>{listingName(l,zh)}</h2><p>{l.origin}{l.destination&&` → ${l.destination}`}</p><strong className="sp-price">{listingPrice(l,zh)}</strong><p className="sp-description">{(zh&&l.description_zh)||l.description}</p><button onClick={()=>setActive(l.id)}>{zh?'联系公司':'Связаться с компанией'}</button>{active===l.id&&<RequestForm listing={l} zh={zh} onCancel={()=>setActive('')}/>}</article>)}</div></section></div>;
}
function CompanyAsset({asset,zh}){
  const [error,setError]=useState(null);
  return <article>{asset.kind==='document'?<button className="secondary" onClick={async()=>{try{await downloadFile('skyvision-company',asset.storage_path,asset.title);}catch(e){setError(e);}}}>PDF · {asset.title}</button>:<><Media bucket="skyvision-company" path={asset.storage_path} kind={asset.kind} label={asset.title}/><p>{asset.title}</p></>}<Feedback error={error} zh={zh}/></article>;
}
function CompanyEditor({companyId,page,assets,zh,onDone}){
  const [v,setV]=useState(page||{about:'',about_zh:'',capacity:'',website:''});const [files,setFiles]=useState([]);const [error,setError]=useState(null);const [busy,setBusy]=useState(false);const [removed,setRemoved]=useState([]);
  async function save(e){e.preventDefault();setBusy(true);setError(null);try{const payload=Object.fromEntries(['about','about_zh','capacity','website'].map(k=>[k,v[k].trim()]));const existing=await result(supabase.from('sv_company_pages').select('company_id').eq('company_id',companyId).maybeSingle());await result(existing?supabase.from('sv_company_pages').update(payload).eq('company_id',companyId):supabase.from('sv_company_pages').insert({...payload,company_id:companyId}));for(const file of files){const path=await uploadFile('skyvision-company',companyId,file,['image/jpeg','image/png','image/webp','video/mp4','video/webm','application/pdf'],50);await result(supabase.from('sv_company_assets').insert({company_id:companyId,title:file.name.slice(0,240),kind:file.type.startsWith('image/')?'photo':file.type.startsWith('video/')?'video':'document',storage_path:path}));setFiles(old=>old.filter(f=>f!==file));}if(removed.length)await result(supabase.from('sv_company_assets').delete().eq('company_id',companyId).in('id',removed));onDone();}catch(e){setError(e);}finally{setBusy(false);}}
  return <form className="sv-card" onSubmit={save}><h2>{zh?'企业展示资料':'Оформление страницы компании'}</h2><div className="sp-fields">{[['about',zh?'介绍（俄文或原文）':'Описание на русском'],['about_zh',zh?'中文介绍':'Описание на китайском']].map(([k,t])=><label key={k}>{t}<textarea value={v[k]} rows={5} maxLength={10000} onChange={e=>setV(old=>({...old,[k]:e.target.value}))}/></label>)}</div><label>{zh?'产能与供应量':'Объёмы и возможности'}<textarea value={v.capacity} maxLength={1000} rows={2} onChange={e=>setV(old=>({...old,capacity:e.target.value}))}/></label><label>{zh?'网站（https://）':'Сайт компании — https://'}<input type="url" pattern="https://.*" value={v.website} onChange={e=>setV(old=>({...old,website:e.target.value}))}/></label><label>{zh?'照片、视频、PDF；每个文件最大50MB':'Фото, видео, PDF — до 50 МБ каждый'}<input type="file" multiple accept=".jpg,.jpeg,.png,.webp,.mp4,.webm,.pdf" onChange={e=>setFiles(Array.from(e.target.files))}/></label><p className="sv-notice">{zh?'这些材料将显示在公开的企业主页。私密合同请上传至供应文件区。':'Эти материалы появятся на публичной странице компании. Закрытые договоры загружайте в документы поставки.'}</p>{assets.filter(a=>!removed.includes(a.id)).map(a=><p key={a.id}>{a.title} <button type="button" className="sp-link" onClick={()=>setRemoved(old=>[...old,a.id])}>{zh?'从主页移除':'Убрать со страницы'}</button></p>)}<Feedback error={error} zh={zh}/><button disabled={busy}>{busy?'…':(zh?'保存主页':'Сохранить страницу')}</button></form>;
}
