import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { supabase } from '../lib/supabaseClient';
import { useCompany } from './CompanyContext';
import { listingName, listingPrice } from './api';
import { Empty, Feedback, Loading, RequestForm, useLoad } from './Portal';

export default function Marketplace({ lang }) {
  const zh = lang === 'zh'; const ctx = useCompany();
  const [kind, setKind] = useState('product'); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [page, setPage] = useState(0); const [active, setActive] = useState('');
  const state = useLoad(async () => {
    let q = supabase.from('sv_listings').select('*,company:sv_companies(name,name_zh,country,city)', { count: 'exact' }).eq('status', 'published').eq('kind', kind).order('updated_at', { ascending: false }).order('id', { ascending: false }).range(page * 20, page * 20 + 19);
    if (query) q = q.or(['title', 'title_zh', 'origin', 'destination'].map(k => `${k}.ilike.%${query}%`).join(','));
    const { data, count, error } = await q; if (error) throw error; return { rows: data, count };
  }, [kind, query, page]);
  function searchNow(e) { e.preventDefault(); setPage(0); setQuery(search.replace(/[%_(),.\\"']/g, ' ').trim().slice(0, 100)); }
  return <div className="sv sp"><div className="sv-heading"><div><span className="sv-eyebrow">SKYVISION MARKETPLACE</span><h1>{zh ? '产品与物流市场' : 'Продукция и логистика'}</h1><p>{zh ? '比较企业报价，直接联系供应商与货运代理。' : 'Предложения компаний. Свяжитесь с заводом или экспедитором напрямую.'}</p></div><Link className="sv-button" to="/portal/listings">+ {zh ? '发布广告' : 'Разместить объявление'}</Link></div><section className="sv-card"><div className="sv-tabs">{[['product', zh ? '工厂产品' : 'Продукция заводов'], ['logistics', zh ? '物流与运输' : 'Логистика и перевозки']].map(([v, label]) => <button key={v} className={kind === v ? 'active' : ''} onClick={() => { setKind(v); setPage(0); setActive(''); }}>{label}</button>)}</div><form className="sp-toolbar" onSubmit={searchNow}><input aria-label={zh ? '搜索广告' : 'Поиск объявлений'} value={search} onChange={e => setSearch(e.target.value)} placeholder={zh ? '产品、城市或车站' : 'Продукция, город или станция'} maxLength={100} /><button>{zh ? '搜索' : 'Найти'}</button>{query && <button className="secondary" type="button" onClick={() => { setQuery(''); setSearch(''); setPage(0); }}>{zh ? '清除' : 'Сбросить'}</button>}</form>{ctx.memberships.length > 0 && <label>{zh ? '代表企业发送申请' : 'Отправлять заявки от компании'}<select value={ctx.company?.id || ''} onChange={e => ctx.select(e.target.value)}>{ctx.memberships.map(m => <option key={m.company_id} value={m.company_id}>{m.company.name}</option>)}</select></label>}</section><Feedback error={state.error} zh={zh} />{state.error && <button onClick={state.reload}>{zh ? '重试' : 'Повторить'}</button>}{state.loading ? <Loading zh={zh} /> : !state.data?.rows.length ? <Empty title={zh ? '暂无符合条件的广告' : 'Объявлений пока нет'} text={zh ? '发布第一条报价，或查看已有工厂目录。' : 'Разместите первое предложение или посмотрите существующий каталог заводов.'}><Link className="sv-button secondary" to="/prices">{zh ? '工厂目录' : 'Каталог заводов'} →</Link></Empty> : <><p className="sv-muted">{zh ? '找到' : 'Найдено'}: {state.data.count}</p><div className="sp-grid">{state.data.rows.map(l => {
    const expired = l.valid_until && l.valid_until < new Date().toLocaleDateString('en-CA');
    return <article className="sv-card sp-listing" key={l.id}><div className="sp-card-top"><span className="sp-kicker">{(zh && l.company?.name_zh) || l.company?.name}</span><span className="sp-tag">{l.company?.country}</span></div><h2>{listingName(l, zh)}</h2><p>{l.origin}{l.destination && ` → ${l.destination}`}</p><div className="sp-tags"><span className="sp-tag">{l.basis === 'route' ? (zh ? '路线运价' : 'Тариф по маршруту') : l.basis}</span>{l.kind === 'logistics' && <span className="sp-tag">{{ rail: zh ? '铁路' : 'Ж/д', road: zh ? '汽车' : 'Авто', container: zh ? '集装箱' : 'Контейнер' }[l.transport]}</span>}<span className="sp-tag">{zh ? '企业尚未认证' : 'Компания не проверена'}</span></div><div className="sp-price">{listingPrice(l, zh)}</div>{l.valid_until && <small className="sv-muted">{zh ? '有效期至' : 'Действует до'} {l.valid_until}{expired ? (zh ? ' · 已过期' : ' · срок истёк') : ''}</small>}<details><summary>{zh ? '详细信息' : 'Подробнее'}</summary><p className="sp-description">{(zh && l.description_zh) || l.description || (zh ? '暂无说明' : 'Описание не добавлено')}</p><small className="sv-muted">{zh ? '更新日期' : 'Обновлено'}: {new Date(l.updated_at).toLocaleDateString(zh ? 'zh-CN' : 'ru-RU')}</small></details><div className="sv-actions"><button disabled={!!expired || ctx.loading} onClick={() => setActive(active === l.id ? '' : l.id)}>{expired ? (zh ? '报价已过期' : 'Предложение истекло') : (zh ? '联系公司' : 'Связаться с компанией')}</button></div>{active === l.id && <RequestForm key={`${l.id}-${ctx.company?.id}`} listing={l} zh={zh} onCancel={() => setActive('')} />}</article>;
  })}</div><div className="sp-pager"><button className="secondary" disabled={page === 0} onClick={() => setPage(p => p - 1)}>←</button><span>{page + 1} / {Math.ceil(state.data.count / 20)}</span><button className="secondary" disabled={(page + 1) * 20 >= state.data.count} onClick={() => setPage(p => p + 1)}>→</button></div></>}</div>;
}
