const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('assert/strict');
const fs = require('fs');
const base = process.env.PORTAL_TEST_URL || 'http://127.0.0.1:4173';
const ids = {a:'ab220000-0000-4000-8000-000000000001',b:'ab220000-0000-4000-8000-000000000002',c:'ab220000-0000-4000-8000-000000000003'};
const photo = { name:'qa-photo.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6X6sAAAAASUVORK5CYII=','base64') };
const pdf = { name:'qa-contract.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Count 0/Kids[]>>endobj\ntrailer<</Root 1 0 R>>\n%%EOF') };
async function login(page,suffix){await page.goto(base+'/network');await page.getByLabel('Email',{exact:true}).fill(`sv-social-qa-${suffix}@example.invalid`);await page.getByLabel('Пароль',{exact:true}).fill(process.env.SOCIAL_QA_PASSWORD);await page.locator('main').getByRole('button',{name:'Войти',exact:true}).click();await page.getByRole('heading',{name:'Находите деловые контакты'}).waitFor({timeout:25000});}
async function profile(page,name){await page.goto(base+'/network/me');await page.getByLabel('Имя и фамилия',{exact:true}).fill(name);await page.getByLabel('Должность / специализация',{exact:true}).fill('Специалист по поставкам');await page.getByLabel(/Фото: JPG/).setInputFiles(photo);const done=page.waitForResponse(r=>r.url().includes('/rest/v1/sv_people')&&['POST','PATCH'].includes(r.request().method()));await page.getByRole('button',{name:'Сохранить профиль',exact:true}).click();assert.equal((await done).ok(),true);await page.waitForTimeout(500);}
(async()=>{
 fs.mkdirSync('qa',{recursive:true});const browser=await chromium.launch({headless:true,channel:'msedge'});const contexts=await Promise.all([0,1,2].map(()=>browser.newContext({viewport:{width:1440,height:1000}})));const [a,b,c]=await Promise.all(contexts.map(x=>x.newPage()));const errors=[];[a,b,c].forEach(p=>p.on('pageerror',e=>errors.push(e.message)));
 try{
  if(process.env.SOCIAL_QA_RESUME_DOCS){await login(a,'a');await login(b,'b');}else{
  await login(a,'a');await profile(a,'QA Арман Агродан');console.log('Profile A + avatar OK');
  await login(b,'b');await profile(b,'QA Ли Покупатель');
  await a.goto(base+'/network/person/'+ids.b);if(await a.getByRole('button',{name:'Добавить в друзья',exact:true}).count()){await a.getByRole('button',{name:'Добавить в друзья',exact:true}).click();await a.getByText('Запрос в друзья отправлен',{exact:true}).waitFor();}
  await b.goto(base+'/network/person/'+ids.a);if(await b.getByRole('button',{name:'Принять запрос',exact:true}).count())await b.getByRole('button',{name:'Принять запрос',exact:true}).click();await b.getByText('Вы в друзьях',{exact:true}).waitFor();
  await a.goto(base+'/network/messages/'+ids.b);await a.getByLabel('Сообщение',{exact:true}).fill('Здравствуйте! Обсудим поставку.');await a.getByRole('button',{name:'Отправить',exact:true}).click();await a.getByText('Здравствуйте! Обсудим поставку.',{exact:true}).first().waitFor();
  await b.goto(base+'/network/messages/'+ids.a);await b.getByText('Здравствуйте! Обсудим поставку.',{exact:true}).first().waitFor({timeout:20000});console.log('Friend acceptance and private messages OK');
  await a.goto(base+'/company/ab220000-0000-4000-8100-000000000001');await a.getByRole('button',{name:'Редактировать страницу компании',exact:true}).click();await a.getByLabel('Описание на русском',{exact:true}).fill('QA Производство кормовой муки');await a.getByLabel('Объёмы и возможности',{exact:true}).fill('1000 тонн в месяц');await a.getByLabel(/Фото, видео, PDF/).setInputFiles([photo,{...pdf,name:'qa-certificate.pdf'}]);await a.getByRole('button',{name:'Сохранить страницу',exact:true}).click();await a.getByText('QA Производство кормовой муки',{exact:true}).waitFor({timeout:30000});await a.getByRole('button',{name:/PDF · qa-certificate/}).waitFor();console.log('Company description, photo and PDF OK');
  }
  await b.goto(base+'/portal/requests/ab220000-0000-4000-8300-000000000001');await b.getByRole('button',{name:'Открыть / создать поставку',exact:true}).click();await b.getByRole('heading',{name:'Документы поставки',exact:true}).waitFor();const dealUrl=b.url();
  await b.getByRole('button',{name:'Добавить документ'}).click();await b.getByLabel('Название документа',{exact:true}).fill('QA Экспортный договор');await b.getByLabel('Номер',{exact:true}).fill('QA-001');await b.getByRole('button',{name:'Создать карточку документа',exact:true}).click();await b.getByRole('heading',{name:'Файлы и версии',exact:true}).waitFor();const docUrl=b.url();
  await b.getByLabel('Файл — до 25 МБ',{exact:true}).setInputFiles(pdf);await b.getByRole('button',{name:'Загрузить версию',exact:true}).click();await b.getByText('v1 · qa-contract.pdf',{exact:true}).waitFor({timeout:30000});
  await b.getByRole('button',{name:'Отправить на согласование',exact:true}).click();await b.getByText('На согласовании',{exact:true}).waitFor();
  await a.goto(docUrl);await a.getByLabel('Комментарий или замечания',{exact:true}).fill('Уточните объём в спецификации.');await a.getByRole('button',{name:'Вернуть на исправление',exact:true}).click();await a.getByText('Нужны исправления',{exact:true}).waitFor();
  await b.reload();await b.getByLabel('Файл — до 25 МБ',{exact:true}).setInputFiles({...pdf,name:'qa-contract-v2.pdf'});await b.getByRole('button',{name:'Загрузить версию',exact:true}).click();await b.getByText('v2 · qa-contract-v2.pdf',{exact:true}).waitFor({timeout:30000});await b.getByRole('button',{name:'Отправить на согласование',exact:true}).click();await b.getByText('На согласовании',{exact:true}).waitFor();
  await a.reload();await a.getByRole('button',{name:'Согласовать',exact:true}).click();await a.getByText('Согласовано',{exact:true}).first().waitFor();await a.getByLabel('Файл — до 25 МБ',{exact:true}).setInputFiles({...pdf,name:'qa-signed.pdf'});await a.getByRole('button',{name:'Загрузить версию',exact:true}).click();await a.getByText('v3 · qa-signed.pdf',{exact:true}).waitFor({timeout:30000});await a.getByText('Загружен подписанный скан',{exact:true}).waitFor();await a.screenshot({path:'qa/document-workflow.png',fullPage:true});console.log('Document upload, revisions, return, approval, signed scan OK');
  const downloadEvent=a.waitForEvent('download');await a.getByRole('button',{name:'Скачать',exact:true}).first().click();const download=await downloadEvent;assert.equal(await download.failure(),null);
  await b.goto(dealUrl);await b.getByLabel('Сообщение поставки',{exact:true}).fill('Сообщение до подключения логиста');await b.getByRole('button',{name:'Отправить',exact:true}).click();await b.getByText('Сообщение до подключения логиста',{exact:true}).waitFor();
  await b.locator('select[name="company"]').selectOption('ab220000-0000-4000-8100-000000000003');await b.getByRole('button',{name:'Пригласить в поставку',exact:true}).click();await b.getByText(/QA Logistics · Ожидает ответа/).waitFor();
  await login(c,'c');await c.goto(base+'/deals');await c.getByRole('button',{name:'Принять',exact:true}).click();await c.getByRole('heading',{name:'Общий чат поставки',exact:true}).waitFor();assert.equal(await c.getByText('Сообщение до подключения логиста',{exact:true}).count(),0);await c.goto(docUrl);await c.getByRole('heading',{name:'Документ недоступен',exact:true}).waitFor();
  await c.goto(dealUrl);await c.getByLabel('Сообщение поставки',{exact:true}).fill('Логист подключился');await c.getByRole('button',{name:'Отправить',exact:true}).click();await b.getByText('Логист подключился',{exact:true}).waitFor({timeout:20000});console.log('Logistics accepted, prior chat and private contract remain hidden OK');
  await b.setViewportSize({width:390,height:844});await b.goto(base+'/network');await b.getByRole('button',{name:'中文',exact:true}).click();await b.getByRole('heading',{name:'建立商务联系',exact:true}).waitFor();assert.equal(await b.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await b.screenshot({path:'qa/social-mobile-zh.png',fullPage:true});assert.deepEqual(errors,[]);console.log('SOCIAL_DOCS_OK');
 }catch(e){console.error(e.message);for(const [i,p]of[a,b,c].entries()){console.error('Page',i,p.url());console.error((await p.locator('main').innerText({timeout:3000}).catch(()=>'' )).slice(-2500));await p.screenshot({path:`qa/social-failure-${i}.png`,fullPage:true}).catch(()=>{});}process.exitCode=1;}finally{await browser.close();}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
