const { chromium }=require(process.env.PLAYWRIGHT_MODULE);
const path=require('path');
const fs=require('fs');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:"msedge"});
  const page=await browser.newPage({viewport:{width:1440,height:1050}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const out=path.resolve(__dirname,'../qa');fs.mkdirSync(out,{recursive:true});
  await page.goto('http://127.0.0.1:4173');
  await page.getByRole('link',{name:/Смотреть заводы и цены/}).waitFor();
  await page.screenshot({path:path.join(out,'home-ru.png'),fullPage:true});
  await page.getByRole('link',{name:/Смотреть заводы и цены/}).click();
  await page.getByRole('link',{name:'Harvest →',exact:true}).waitFor();
  if(await page.locator('tbody tr').count()!==15)throw new Error('Expected 15 factories');
  await page.screenshot({path:path.join(out,'prices-ru.png'),fullPage:true});
  await page.getByRole('link',{name:'Harvest →',exact:true}).click();
  await page.getByRole('heading',{name:'Harvest',exact:true}).waitFor();
  await page.screenshot({path:path.join(out,'harvest-ru.png'),fullPage:true});
  await page.getByRole('button',{name:'中文',exact:true}).click();
  await page.getByRole('heading',{name:'产品与价格',exact:true}).waitFor();
  await page.getByRole('button',{name:'询价',exact:true}).click();
  await page.getByRole('dialog').waitFor();
  if(await page.getByRole('textbox',{name:'产品',exact:true}).inputValue()!=='饲料面粉')throw new Error('Product context lost');
  await page.screenshot({path:path.join(out,'inquiry-zh.png'),fullPage:true});
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.goto('http://127.0.0.1:4173/prices');
  await page.getByRole('link',{name:'Harvest →',exact:true}).waitFor();
  await page.screenshot({path:path.join(out,'prices-mobile-zh.png'),fullPage:true});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1))throw new Error('Mobile page overflows');
  await page.setViewportSize({width:1440,height:1050});
  await page.getByRole('button',{name:'RU',exact:true}).click();
  if(process.env.SKYVISION_TEST_PASSWORD){
    await page.getByRole('button',{name:'Войти',exact:true}).click();
    await page.getByPlaceholder('Email администратора').fill(process.env.SKYVISION_TEST_EMAIL);
    await page.getByPlaceholder('Пароль',{exact:true}).fill(process.env.SKYVISION_TEST_PASSWORD);
    await page.locator('.admin-login-form').getByRole('button',{name:'Войти',exact:true}).click();
    await page.getByRole('button',{name:'Админ',exact:true}).waitFor();
    await page.goto('http://127.0.0.1:4173/admin/factories');
    await page.getByRole('heading',{name:'Каталог заводов',exact:true}).waitFor();
    await page.screenshot({path:path.join(out,'admin-list.png'),fullPage:true});
    await page.getByRole('link',{name:'Harvest',exact:true}).click();
    await page.getByRole('heading',{name:'Информация о заводе',exact:true}).waitFor();
    await page.screenshot({path:path.join(out,'admin-editor.png'),fullPage:true});
    await page.getByRole('button',{name:/04.*Фото и видео/}).click();
    await page.screenshot({path:path.join(out,'admin-media.png'),fullPage:true});
    await page.getByRole('button',{name:'Предпросмотр →',exact:true}).click();
    await page.getByLabel('Язык предпросмотра').selectOption('zh');
    await page.getByRole('heading',{name:'产品与价格',exact:true}).waitFor();
  }
  await browser.close();
  if(errors.length)throw new Error(errors.join('\n'));
  console.log('UI checks passed: home, 15 factories, media, language, inquiry context, mobile, admin (when credentials provided).');
})().catch(e=>{console.error(e.message);process.exit(1);});
